---
title: a03 classification models
author: ''
date: '2022-04-02'
slug: a03-classification-models
categories: []
tags: []
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<div id="executive-summary" class="section level1">
<h1>Executive Summary</h1>
<div id="the-titanic-ship-sinking-was-a-great-tragedy-in-history.-the-tragedy-has-generated-data-on-which-passenger-survived-and-which-did-not.-in-addition-to-this-data-other-data-has-been-collected-for-each-passenger-such-as-sexname-and-fare-amongst-other-identifiers.-the-goal-is-to-build-a-logistic-model-that-predicts-which-passengers-survive-and-which-die." class="section level3">
<h3>The Titanic ship sinking was a great tragedy in history. The tragedy has generated data on which passenger survived and which did not. In addition to this data, other data has been collected for each passenger such as sex,name, and fare amongst other identifiers. The goal is to build a logistic model that predicts which passengers survive and which die.</h3>
</div>
</div>
<div id="issues-and-challenges" class="section level1">
<h1>Issues and challenges</h1>
<div id="the-immediate-challenge-is-to-pick-which-variables-to-use-for-this-logistic-regression-model-as-not-all-variables-will-be-high-yield-predictors." class="section level3">
<h3>The immediate challenge is to pick which variables to use for this logistic regression model as not all variables will be high yield predictors.</h3>
</div>
</div>
<div id="setup" class="section level1">
<h1>Setup</h1>
<pre class="r"><code>if(!require(&quot;pacman&quot;)) install.packages(&quot;pacman&quot;)</code></pre>
<pre><code>## Loading required package: pacman</code></pre>
<pre><code>## Warning: package &#39;pacman&#39; was built under R version 4.1.3</code></pre>
<pre class="r"><code>pacman::p_load(pacman,readxl, magrittr, productplots, psych, RColorBrewer, tidyverse, boot, InformationValue,caret)
train &lt;- read_csv(&quot;https://raw.githubusercontent.com/vsomesula/COPwebsite/main/content/post/2022-04-02-a03-classification-models/train.csv&quot;)</code></pre>
<pre><code>## Rows: 891 Columns: 12</code></pre>
<pre><code>## -- Column specification --------------------------------------------------------
## Delimiter: &quot;,&quot;
## chr (5): Name, Sex, Ticket, Cabin, Embarked
## dbl (7): PassengerId, Survived, Pclass, Age, SibSp, Parch, Fare
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>test &lt;- read_csv(&quot;https://raw.githubusercontent.com/vsomesula/COPwebsite/main/content/post/2022-04-02-a03-classification-models/test.csv&quot;)</code></pre>
<pre><code>## Rows: 418 Columns: 11
## -- Column specification --------------------------------------------------------
## Delimiter: &quot;,&quot;
## chr (5): Name, Sex, Ticket, Cabin, Embarked
## dbl (6): PassengerId, Pclass, Age, SibSp, Parch, Fare
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>submission &lt;- read_csv(&quot;https://raw.githubusercontent.com/vsomesula/COPwebsite/main/content/post/2022-04-02-a03-classification-models/submission.csv&quot;)</code></pre>
<pre><code>## Rows: 418 Columns: 2
## -- Column specification --------------------------------------------------------
## Delimiter: &quot;,&quot;
## dbl (2): PassengerId, Survived
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>attach(train)</code></pre>
</div>
<div id="exploratory-data-analyis" class="section level1">
<h1>Exploratory Data Analyis</h1>
<div id="we-gain-a-sense-of-what-the-variables-are-in-this-dataset.-some-variables-we-can-automatically-excluse-just-from-a-cursory-glance-of-the-dataset-such-as-name-passengerid-ticket-and-cabin." class="section level3">
<h3>We gain a sense of what the variables are in this dataset. Some variables we can automatically excluse just from a cursory glance of the dataset such as Name, PassengerId, Ticket, and Cabin.</h3>
<pre class="r"><code>glimpse(train)</code></pre>
<pre><code>## Rows: 891
## Columns: 12
## $ PassengerId &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,~
## $ Survived    &lt;dbl&gt; 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1~
## $ Pclass      &lt;dbl&gt; 3, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1, 3, 3, 3, 2, 3, 2, 3, 3~
## $ Name        &lt;chr&gt; &quot;Braund, Mr. Owen Harris&quot;, &quot;Cumings, Mrs. John Bradley (Fl~
## $ Sex         &lt;chr&gt; &quot;male&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;male&quot;, &quot;male&quot;, &quot;mal~
## $ Age         &lt;dbl&gt; 22, 38, 26, 35, 35, NA, 54, 2, 27, 14, 4, 58, 20, 39, 14, ~
## $ SibSp       &lt;dbl&gt; 1, 1, 0, 1, 0, 0, 0, 3, 0, 1, 1, 0, 0, 1, 0, 0, 4, 0, 1, 0~
## $ Parch       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 5, 0, 0, 1, 0, 0, 0~
## $ Ticket      &lt;chr&gt; &quot;A/5 21171&quot;, &quot;PC 17599&quot;, &quot;STON/O2. 3101282&quot;, &quot;113803&quot;, &quot;37~
## $ Fare        &lt;dbl&gt; 7.2500, 71.2833, 7.9250, 53.1000, 8.0500, 8.4583, 51.8625,~
## $ Cabin       &lt;chr&gt; NA, &quot;C85&quot;, NA, &quot;C123&quot;, NA, NA, &quot;E46&quot;, NA, NA, NA, &quot;G6&quot;, &quot;C~
## $ Embarked    &lt;chr&gt; &quot;S&quot;, &quot;C&quot;, &quot;S&quot;, &quot;S&quot;, &quot;S&quot;, &quot;Q&quot;, &quot;S&quot;, &quot;S&quot;, &quot;S&quot;, &quot;C&quot;, &quot;S&quot;, &quot;S&quot;~</code></pre>
</div>
</div>
<div id="build-a-logistic-model-with-all-the-variables" class="section level1">
<h1>Build a logistic model with all the variables</h1>
<div id="doin-so-allows-us-to-gain-the-p-values-for-each-variable-allowing-us-to-determine-which-variables-are-high-yield-predictors-and-which-are-not" class="section level3">
<h3>Doin so allows us to gain the p-values for each variable allowing us to determine which variables are high-yield predictors and which are not</h3>
<pre class="r"><code>model &lt;- glm(formula = Survived~Pclass+Sex+Age+SibSp+Parch+Fare+Embarked, data = train, family = &#39;binomial&#39;)
summary(model)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Survived ~ Pclass + Sex + Age + SibSp + Parch + 
##     Fare + Embarked, family = &quot;binomial&quot;, data = train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7233  -0.6447  -0.3799   0.6326   2.4457  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  5.637407   0.634550   8.884  &lt; 2e-16 ***
## Pclass      -1.199251   0.164619  -7.285 3.22e-13 ***
## Sexmale     -2.638476   0.222256 -11.871  &lt; 2e-16 ***
## Age         -0.043350   0.008232  -5.266 1.39e-07 ***
## SibSp       -0.363208   0.129017  -2.815  0.00487 ** 
## Parch       -0.060270   0.123900  -0.486  0.62666    
## Fare         0.001432   0.002531   0.566  0.57165    
## EmbarkedQ   -0.823545   0.600229  -1.372  0.17005    
## EmbarkedS   -0.401213   0.270283  -1.484  0.13770    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 960.90  on 711  degrees of freedom
## Residual deviance: 632.34  on 703  degrees of freedom
##   (179 observations deleted due to missingness)
## AIC: 650.34
## 
## Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div id="using-the-p-values-for-each-of-the-variables-we-can-see-how-pclass-sex-age-and-sibsp-are-very-good-predictors-of-surival-rate-embarked-is-a-mediocre-predictor-and-fare-is-a-poor-predictor." class="section level3">
<h3>Using the p-values for each of the variables we can see how Pclass, Sex, Age, and SibSP, are very good predictors of surival rate, Embarked is a mediocre predictor and Fare is a poor predictor.</h3>
</div>
<div id="to-further-determine-the-order-of-which-variable-is-a-good-predictor-and-which-is-a-poor-predictor-we-can-use-the-caret-package." class="section level3">
<h3>To further determine the order of which variable is a good predictor and which is a poor predictor we can use the caret package.</h3>
<pre class="r"><code>caret::varImp(model)</code></pre>
<pre><code>##              Overall
## Pclass     7.2850090
## Sexmale   11.8713151
## Age        5.2659747
## SibSp      2.8151950
## Parch      0.4864374
## Fare       0.5656293
## EmbarkedQ  1.3720511
## EmbarkedS  1.4844172</code></pre>
</div>
<div id="a-higher-value-means-more-importance-for-that-variable.-with-this-information-we-can-see-that-the-order-of-how-important-each-variable-is-sex-pclass-age-and-sibsp.-embarked-could-be-included-but-is-not-likly-to-add-much-value-especially-since-if-we-obserbe-the-p-values-above-they-are-both-above-0.1-which-mains-most-scientists-would-consider-them-not-significant.-additionally-parch-and-fare-can-be-completly-excluded-as-their-values-are-much-lower-than-the-good-predictors-such-as-pclass." class="section level3">
<h3>A higher value means more importance for that variable. With this information, we can see that the order of how important each variable is Sex, Pclass, Age, and SibSp. Embarked could be included but is not likly to add much value (Especially, since if we obserbe the p-values above they are both above 0.1 which mains most scientists would consider them not significant). Additionally, Parch and Fare can be completly excluded as their values are much lower than the good predictors such as Pclass.</h3>
</div>
<div id="it-is-important-to-note-that-since-not-all-passengers-have-age-data-we-can-not-include-this-important-variable-in-those-model.-having-that-data-point-would-cause-there-to-be-nas-for-some-of-the-passangers-who-do-not-have-thar-variable." class="section level3">
<h3>It is important to note that since not all passengers have age data we can not include this important variable in those model. Having that data point would cause there to be NA’s for some of the passangers who do not have thar variable.</h3>
</div>
</div>
<div id="building-a-logistic-model-with-all-variables-determined-to-be-important" class="section level1">
<h1>Building a logistic model with all variables determined to be important</h1>
<pre class="r"><code>model &lt;- glm(formula = Survived~Pclass+Sex+SibSp, data = train, family = &#39;binomial&#39;)
summary(model)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Survived ~ Pclass + Sex + SibSp, family = &quot;binomial&quot;, 
##     data = train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.2689  -0.6735  -0.4747   0.6189   2.5148  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  3.43357    0.30543  11.242  &lt; 2e-16 ***
## Pclass      -0.93896    0.10647  -8.819  &lt; 2e-16 ***
## Sexmale     -2.74314    0.19027 -14.417  &lt; 2e-16 ***
## SibSp       -0.24812    0.09453  -2.625  0.00867 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1186.66  on 890  degrees of freedom
## Residual deviance:  819.32  on 887  degrees of freedom
## AIC: 827.32
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div id="once-again-we-can-obserbe-the-p-values-being-signficant-for-the-variables-we-selected.-we-can-see-that-this-model-is-a-better-predictor-than-a-model-with-all-the-variables-since-the-aic-is-lower-for-the-new-model." class="section level3">
<h3>Once again, we can obserbe the p-values being signficant for the variables we selected. We can see that this model is a better predictor than a model with all the variables since the AIC is lower for the new model.</h3>
</div>
</div>
<div id="applying-the-model-to-the-test-data-set-to-predict-survivors" class="section level1">
<h1>Applying the model to the test data set to predict survivors</h1>
<div id="the-data-may-not-display-properly-due-to-the-long-names-of-the-passengners-however-the-output-is-a-dataframe-with-dimensions-418-x-3." class="section level4">
<h4>The data may not display properly due to the long names of the passengners, however, the output is a dataframe with dimensions 418 x 3.</h4>
<pre class="r"><code>predictions &lt;- predict(model, test, type = &quot;response&quot;)
output &lt;- data.frame(test$PassengerId, test$Name, Survived = predictions )
output</code></pre>
<pre><code>##     test.PassengerId
## 1                892
## 2                893
## 3                894
## 4                895
## 5                896
## 6                897
## 7                898
## 8                899
## 9                900
## 10               901
## 11               902
## 12               903
## 13               904
## 14               905
## 15               906
## 16               907
## 17               908
## 18               909
## 19               910
## 20               911
## 21               912
## 22               913
## 23               914
## 24               915
## 25               916
## 26               917
## 27               918
## 28               919
## 29               920
## 30               921
## 31               922
## 32               923
## 33               924
## 34               925
## 35               926
## 36               927
## 37               928
## 38               929
## 39               930
## 40               931
## 41               932
## 42               933
## 43               934
## 44               935
## 45               936
## 46               937
## 47               938
## 48               939
## 49               940
## 50               941
## 51               942
## 52               943
## 53               944
## 54               945
## 55               946
## 56               947
## 57               948
## 58               949
## 59               950
## 60               951
## 61               952
## 62               953
## 63               954
## 64               955
## 65               956
## 66               957
## 67               958
## 68               959
## 69               960
## 70               961
## 71               962
## 72               963
## 73               964
## 74               965
## 75               966
## 76               967
## 77               968
## 78               969
## 79               970
## 80               971
## 81               972
## 82               973
## 83               974
## 84               975
## 85               976
## 86               977
## 87               978
## 88               979
## 89               980
## 90               981
## 91               982
## 92               983
## 93               984
## 94               985
## 95               986
## 96               987
## 97               988
## 98               989
## 99               990
## 100              991
## 101              992
## 102              993
## 103              994
## 104              995
## 105              996
## 106              997
## 107              998
## 108              999
## 109             1000
## 110             1001
## 111             1002
## 112             1003
## 113             1004
## 114             1005
## 115             1006
## 116             1007
## 117             1008
## 118             1009
## 119             1010
## 120             1011
## 121             1012
## 122             1013
## 123             1014
## 124             1015
## 125             1016
## 126             1017
## 127             1018
## 128             1019
## 129             1020
## 130             1021
## 131             1022
## 132             1023
## 133             1024
## 134             1025
## 135             1026
## 136             1027
## 137             1028
## 138             1029
## 139             1030
## 140             1031
## 141             1032
## 142             1033
## 143             1034
## 144             1035
## 145             1036
## 146             1037
## 147             1038
## 148             1039
## 149             1040
## 150             1041
## 151             1042
## 152             1043
## 153             1044
## 154             1045
## 155             1046
## 156             1047
## 157             1048
## 158             1049
## 159             1050
## 160             1051
## 161             1052
## 162             1053
## 163             1054
## 164             1055
## 165             1056
## 166             1057
## 167             1058
## 168             1059
## 169             1060
## 170             1061
## 171             1062
## 172             1063
## 173             1064
## 174             1065
## 175             1066
## 176             1067
## 177             1068
## 178             1069
## 179             1070
## 180             1071
## 181             1072
## 182             1073
## 183             1074
## 184             1075
## 185             1076
## 186             1077
## 187             1078
## 188             1079
## 189             1080
## 190             1081
## 191             1082
## 192             1083
## 193             1084
## 194             1085
## 195             1086
## 196             1087
## 197             1088
## 198             1089
## 199             1090
## 200             1091
## 201             1092
## 202             1093
## 203             1094
## 204             1095
## 205             1096
## 206             1097
## 207             1098
## 208             1099
## 209             1100
## 210             1101
## 211             1102
## 212             1103
## 213             1104
## 214             1105
## 215             1106
## 216             1107
## 217             1108
## 218             1109
## 219             1110
## 220             1111
## 221             1112
## 222             1113
## 223             1114
## 224             1115
## 225             1116
## 226             1117
## 227             1118
## 228             1119
## 229             1120
## 230             1121
## 231             1122
## 232             1123
## 233             1124
## 234             1125
## 235             1126
## 236             1127
## 237             1128
## 238             1129
## 239             1130
## 240             1131
## 241             1132
## 242             1133
## 243             1134
## 244             1135
## 245             1136
## 246             1137
## 247             1138
## 248             1139
## 249             1140
## 250             1141
## 251             1142
## 252             1143
## 253             1144
## 254             1145
## 255             1146
## 256             1147
## 257             1148
## 258             1149
## 259             1150
## 260             1151
## 261             1152
## 262             1153
## 263             1154
## 264             1155
## 265             1156
## 266             1157
## 267             1158
## 268             1159
## 269             1160
## 270             1161
## 271             1162
## 272             1163
## 273             1164
## 274             1165
## 275             1166
## 276             1167
## 277             1168
## 278             1169
## 279             1170
## 280             1171
## 281             1172
## 282             1173
## 283             1174
## 284             1175
## 285             1176
## 286             1177
## 287             1178
## 288             1179
## 289             1180
## 290             1181
## 291             1182
## 292             1183
## 293             1184
## 294             1185
## 295             1186
## 296             1187
## 297             1188
## 298             1189
## 299             1190
## 300             1191
## 301             1192
## 302             1193
## 303             1194
## 304             1195
## 305             1196
## 306             1197
## 307             1198
## 308             1199
## 309             1200
## 310             1201
## 311             1202
## 312             1203
## 313             1204
## 314             1205
## 315             1206
## 316             1207
## 317             1208
## 318             1209
## 319             1210
## 320             1211
## 321             1212
## 322             1213
## 323             1214
## 324             1215
## 325             1216
## 326             1217
## 327             1218
## 328             1219
## 329             1220
## 330             1221
## 331             1222
## 332             1223
## 333             1224
## 334             1225
## 335             1226
## 336             1227
## 337             1228
## 338             1229
## 339             1230
## 340             1231
## 341             1232
## 342             1233
## 343             1234
## 344             1235
## 345             1236
## 346             1237
## 347             1238
## 348             1239
## 349             1240
## 350             1241
## 351             1242
## 352             1243
## 353             1244
## 354             1245
## 355             1246
## 356             1247
## 357             1248
## 358             1249
## 359             1250
## 360             1251
## 361             1252
## 362             1253
## 363             1254
## 364             1255
## 365             1256
## 366             1257
## 367             1258
## 368             1259
## 369             1260
## 370             1261
## 371             1262
## 372             1263
## 373             1264
## 374             1265
## 375             1266
## 376             1267
## 377             1268
## 378             1269
## 379             1270
## 380             1271
## 381             1272
## 382             1273
## 383             1274
## 384             1275
## 385             1276
## 386             1277
## 387             1278
## 388             1279
## 389             1280
## 390             1281
## 391             1282
## 392             1283
## 393             1284
## 394             1285
## 395             1286
## 396             1287
## 397             1288
## 398             1289
## 399             1290
## 400             1291
## 401             1292
## 402             1293
## 403             1294
## 404             1295
## 405             1296
## 406             1297
## 407             1298
## 408             1299
## 409             1300
## 410             1301
## 411             1302
## 412             1303
## 413             1304
## 414             1305
## 415             1306
## 416             1307
## 417             1308
## 418             1309
##                                                           test.Name   Survived
## 1                                                  Kelly, Mr. James 0.10655287
## 2                                  Wilkes, Mrs. James (Ellen Needs) 0.59111294
## 3                                         Myles, Mr. Thomas Francis 0.23370898
## 4                                                  Wirz, Mr. Albert 0.10655287
## 5                      Hirvonen, Mrs. Alexander (Helga E Lindqvist) 0.59111294
## 6                                        Svensson, Mr. Johan Cervin 0.10655287
## 7                                              Connolly, Miss. Kate 0.64946522
## 8                                      Caldwell, Mr. Albert Francis 0.19222661
## 9                         Abrahim, Mrs. Joseph (Sophie Halaut Easu) 0.64946522
## 10                                          Davies, Mr. John Samuel 0.06769243
## 11                                                 Ilieff, Mr. Ylio 0.10655287
## 12                                       Jones, Mr. Charles Cresson 0.43818663
## 13                    Snyder, Mrs. John Pillsbury (Nelle Stevenson) 0.90434727
## 14                                             Howard, Mr. Benjamin 0.19222661
## 15          Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood) 0.90434727
## 16                    del Carlo, Mrs. Sebastiano (Argenia Genovesi) 0.78709932
## 17                                                Keane, Mr. Daniel 0.23370898
## 18                                                Assaf, Mr. Gerios 0.10655287
## 19                                     Ilmakangas, Miss. Ida Livija 0.59111294
## 20                            Assaf Khalil, Mrs. Mariana (Miriam&quot;)&quot; 0.64946522
## 21                                           Rothschild, Mr. Martin 0.37832918
## 22                                        Olsen, Master. Artur Karl 0.10655287
## 23                             Flegenheim, Mrs. Alfred (Antoinette) 0.92376313
## 24                                  Williams, Mr. Richard Norris II 0.43818663
## 25                  Ryerson, Mrs. Arthur Larned (Emily Maria Borie) 0.90434727
## 26                                          Robins, Mr. Alexander A 0.08513275
## 27                                     Ostby, Miss. Helene Ragnhild 0.92376313
## 28                                                Daher, Mr. Shedid 0.10655287
## 29                                          Brady, Mr. John Bertram 0.43818663
## 30                                                Samaan, Mr. Elias 0.06769243
## 31                                     Louch, Mr. Charles Alexander 0.19222661
## 32                                    Jefferys, Mr. Clifford Thomas 0.15660247
## 33                         Dean, Mrs. Bertram (Eva Georgetta Light) 0.59111294
## 34                Johnston, Mrs. Andrew G (Elizabeth Lily&quot; Watson)&quot; 0.59111294
## 35                                         Mock, Mr. Philipp Edmund 0.37832918
## 36                 Katavelas, Mr. Vassilios (Catavelas Vassilios&quot;)&quot; 0.10655287
## 37                                              Roth, Miss. Sarah A 0.64946522
## 38                                               Cacic, Miss. Manda 0.64946522
## 39                                                  Sap, Mr. Julius 0.10655287
## 40                                                    Hee, Mr. Ling 0.10655287
## 41                                                 Karun, Mr. Franz 0.10655287
## 42                                      Franklin, Mr. Thomas Parham 0.43818663
## 43                                            Goldsmith, Mr. Nathan 0.10655287
## 44                            Corbett, Mrs. Walter H (Irene Colvin) 0.82572825
## 45                 Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons) 0.90434727
## 46                                  Peltomaki, Mr. Nikolai Johannes 0.10655287
## 47                                         Chevre, Mr. Paul Romaine 0.43818663
## 48                                         Shaughnessy, Mr. Patrick 0.10655287
## 49                  Bucknell, Mrs. William Robert (Emma Eliza Ward) 0.92376313
## 50                   Coutts, Mrs. William (Winnie Minnie&quot; Treanor)&quot; 0.64946522
## 51                                         Smith, Mr. Lucien Philip 0.37832918
## 52                                               Pulbaum, Mr. Franz 0.23370898
## 53                                    Hocking, Miss. Ellen Nellie&quot;&quot; 0.74257728
## 54                                       Fortune, Miss. Ethel Flora 0.85198391
## 55                                Mangiavacchi, Mr. Serafino Emilio 0.23370898
## 56                                             Rice, Master. Albert 0.04233309
## 57                                                  Cor, Mr. Bartol 0.10655287
## 58                                    Abelseth, Mr. Olaus Jorgensen 0.10655287
## 59                                        Davison, Mr. Thomas Henry 0.08513275
## 60                                      Chaudanson, Miss. Victorine 0.92376313
## 61                                                  Dika, Mr. Mirko 0.10655287
## 62                                        McCrae, Mr. Arthur Gordon 0.23370898
## 63                                     Bjorklund, Mr. Ernst Herbert 0.10655287
## 64                                     Bradley, Miss. Bridget Delia 0.64946522
## 65                                      Ryerson, Master. John Borie 0.32196255
## 66              Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller) 0.82572825
## 67                                          Burns, Miss. Mary Delia 0.64946522
## 68                                   Moore, Mr. Clarence Bloomfield 0.43818663
## 69                                  Tucker, Mr. Gilbert Milligan Jr 0.43818663
## 70                              Fortune, Mrs. Mark (Mary McDougald) 0.90434727
## 71                                        Mulvihill, Miss. Bertha E 0.64946522
## 72                                               Minkoff, Mr. Lazar 0.10655287
## 73                                   Nieminen, Miss. Manta Josefina 0.64946522
## 74                                  Ovies y Rodriguez, Mr. Servando 0.43818663
## 75                                             Geiger, Miss. Amalie 0.92376313
## 76                                               Keeping, Mr. Edwin 0.43818663
## 77                                                 Miles, Mr. Frank 0.10655287
## 78             Cornell, Mrs. Robert Clifford (Malvina Helen Lamson) 0.88062562
## 79                                   Aldworth, Mr. Charles Augustus 0.23370898
## 80                                           Doyle, Miss. Elizabeth 0.64946522
## 81                                             Boulos, Master. Akar 0.08513275
## 82                                               Straus, Mr. Isidor 0.37832918
## 83                                           Case, Mr. Howard Brown 0.43818663
## 84                                             Demetri, Mr. Marinko 0.10655287
## 85                                            Lamb, Mr. John Joseph 0.23370898
## 86                                               Khalil, Mr. Betros 0.08513275
## 87                                               Barry, Miss. Julia 0.64946522
## 88                                       Badman, Miss. Emily Louisa 0.64946522
## 89                                          O&#39;Donoghue, Ms. Bridget 0.64946522
## 90                                      Wells, Master. Ralph Lester 0.19222661
## 91      Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judith Andersson) 0.59111294
## 92                                               Pedersen, Mr. Olaf 0.10655287
## 93                             Davidson, Mrs. Thornton (Orian Hays) 0.90434727
## 94                                                Guest, Mr. Robert 0.10655287
## 95                                              Birnbaum, Mr. Jakob 0.43818663
## 96                                       Tenglin, Mr. Gunnar Isidor 0.10655287
## 97           Cavendish, Mrs. Tyrell William (Julia Florence Siegel) 0.90434727
## 98                                        Makinen, Mr. Kalle Edvard 0.10655287
## 99                                     Braf, Miss. Elin Ester Maria 0.64946522
## 100                                    Nancarrow, Mr. William Henry 0.10655287
## 101             Stengel, Mrs. Charles Emil Henry (Annie May Morris) 0.90434727
## 102                                              Weisz, Mr. Leopold 0.19222661
## 103                                              Foley, Mr. William 0.10655287
## 104                          Johansson Palmquist, Mr. Oskar Leander 0.10655287
## 105                       Thomas, Mrs. Alexander (Thamine Thelma&quot;)&quot; 0.59111294
## 106                                       Holthen, Mr. Johan Martin 0.10655287
## 107                                             Buckley, Mr. Daniel 0.10655287
## 108                                                Ryan, Mr. Edward 0.10655287
## 109                                Willer, Mr. Aaron (Abi Weller&quot;)&quot; 0.10655287
## 110                                               Swane, Mr. George 0.23370898
## 111                                        Stanton, Mr. Samuel Ward 0.23370898
## 112                                      Shine, Miss. Ellen Natalia 0.64946522
## 113                                        Evans, Miss. Edith Corse 0.92376313
## 114                                        Buckley, Miss. Katherine 0.64946522
## 115                          Straus, Mrs. Isidor (Rosalie Ida Blun) 0.90434727
## 116                                     Chronopoulos, Mr. Demetrios 0.08513275
## 117                                                Thomas, Mr. John 0.10655287
## 118                                 Sandstrom, Miss. Beatrice Irene 0.59111294
## 119                                            Beattie, Mr. Thomson 0.43818663
## 120                 Chapman, Mrs. John Henry (Sara Elizabeth Lawry) 0.78709932
## 121                                            Watt, Miss. Bertha J 0.82572825
## 122                                               Kiernan, Mr. John 0.08513275
## 123                                 Schabert, Mrs. Paul (Emma Mock) 0.90434727
## 124                                         Carver, Mr. Alfred John 0.10655287
## 125                                               Kennedy, Mr. John 0.10655287
## 126                                        Cribb, Miss. Laura Alice 0.64946522
## 127                                        Brobeck, Mr. Karl Rudolf 0.10655287
## 128                                             McCoy, Miss. Alicia 0.53007536
## 129                                            Bowenur, Mr. Solomon 0.23370898
## 130                                            Petersen, Mr. Marius 0.10655287
## 131                                         Spinner, Mr. Henry John 0.10655287
## 132                                       Gracie, Col. Archibald IV 0.43818663
## 133                                   Lefebre, Mrs. Frank (Frances) 0.64946522
## 134                                           Thomas, Mr. Charles P 0.08513275
## 135                                          Dintcheff, Mr. Valtcho 0.10655287
## 136                                       Carlsson, Mr. Carl Robert 0.10655287
## 137                                       Zakarian, Mr. Mapriededer 0.10655287
## 138                                             Schmidt, Mr. August 0.23370898
## 139                                           Drapkin, Miss. Jennie 0.64946522
## 140                                  Goodwin, Mr. Charles Frederick 0.08513275
## 141                                     Goodwin, Miss. Jessie Allis 0.34889114
## 142                                            Daniels, Miss. Sarah 0.92376313
## 143                                      Ryerson, Mr. Arthur Larned 0.37832918
## 144                                      Beauchamp, Mr. Henry James 0.23370898
## 145           Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lingrey&quot;)&quot; 0.43818663
## 146                                       Vander Planke, Mr. Julius 0.05361555
## 147                                     Hilliard, Mr. Herbert Henry 0.43818663
## 148                                                Davies, Mr. Evan 0.10655287
## 149                                       Crafton, Mr. John Bertram 0.43818663
## 150                                          Lahtinen, Rev. William 0.19222661
## 151                           Earnshaw, Mrs. Boulton (Olive Potter) 0.92376313
## 152                                            Matinoff, Mr. Nicola 0.10655287
## 153                                              Storey, Mr. Thomas 0.10655287
## 154                  Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist) 0.64946522
## 155                                    Asplund, Master. Filip Oscar 0.04233309
## 156                                            Duquemin, Mr. Joseph 0.10655287
## 157                                               Bird, Miss. Ellen 0.92376313
## 158                                        Lundin, Miss. Olga Elida 0.64946522
## 159                                        Borebank, Mr. John James 0.43818663
## 160                             Peacock, Mrs. Benjamin (Edith Nile) 0.64946522
## 161                                              Smyth, Miss. Julia 0.64946522
## 162                                  Touma, Master. Georges Youssef 0.08513275
## 163                                            Wright, Miss. Marion 0.82572825
## 164                                              Pearce, Mr. Ernest 0.10655287
## 165                                   Peruschitz, Rev. Joseph Maria 0.23370898
## 166                      Kink-Heilmann, Mrs. Anton (Luise Heilmann) 0.59111294
## 167                                              Brandeis, Mr. Emil 0.43818663
## 168                                         Ford, Mr. Edward Watson 0.06769243
## 169     Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick) 0.92376313
## 170                                    Hellstrom, Miss. Hilda Maria 0.64946522
## 171                                              Lithman, Mr. Simon 0.10655287
## 172                                             Zakarian, Mr. Ortin 0.10655287
## 173                                        Dyker, Mr. Adolf Fredrik 0.08513275
## 174                                                Torfa, Mr. Assad 0.10655287
## 175                      Asplund, Mr. Carl Oscar Vilhelm Gustafsson 0.08513275
## 176                                       Brown, Miss. Edith Eileen 0.82572825
## 177                                            Sincock, Miss. Maude 0.82572825
## 178                                 Stengel, Mr. Charles Emil Henry 0.37832918
## 179                Becker, Mrs. Allen Oliver (Nellie E Baumgardner) 0.82572825
## 180           Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll) 0.92376313
## 181                                       McCrie, Mr. James Matthew 0.23370898
## 182                                Compton, Mr. Alexander Taylor Jr 0.37832918
## 183  Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson) 0.90434727
## 184                                               Lane, Mr. Patrick 0.10655287
## 185            Douglas, Mrs. Frederick Charles (Mary Helene Baxter) 0.90434727
## 186                                       Maybery, Mr. Frank Hubert 0.23370898
## 187                            Phillips, Miss. Alice Frances Louisa 0.82572825
## 188                                              Davies, Mr. Joseph 0.06769243
## 189                                                 Sage, Miss. Ada 0.20289778
## 190                                                 Veal, Mr. James 0.23370898
## 191                                            Angle, Mr. William A 0.19222661
## 192                                          Salomon, Mr. Abraham L 0.43818663
## 193                               van Billiard, Master. Walter John 0.08513275
## 194                                               Lingane, Mr. John 0.23370898
## 195                                   Drew, Master. Marshall Brines 0.23370898
## 196                               Karlsson, Mr. Julius Konrad Eugen 0.10655287
## 197                                 Spedden, Master. Robert Douglas 0.43818663
## 198                                     Nilsson, Miss. Berta Olivia 0.64946522
## 199                                  Baimbrigge, Mr. Charles Robert 0.23370898
## 200                         Rasmussen, Mrs. (Lena Jacobsen Solvang) 0.64946522
## 201                                              Murphy, Miss. Nora 0.64946522
## 202                         Danbom, Master. Gilbert Sigvard Emanuel 0.10655287
## 203                                          Astor, Col. John Jacob 0.37832918
## 204                                      Quick, Miss. Winifred Vera 0.78709932
## 205                                        Andrew, Mr. Frank Thomas 0.23370898
## 206                                       Omont, Mr. Alfred Fernand 0.43818663
## 207                                        McGowan, Miss. Katherine 0.64946522
## 208                                    Collett, Mr. Sidney C Stuart 0.23370898
## 209                                   Rosenbaum, Miss. Edith Louise 0.92376313
## 210                                              Delalic, Mr. Redjo 0.10655287
## 211                                     Andersen, Mr. Albert Karvin 0.10655287
## 212                                               Finoli, Mr. Luigi 0.10655287
## 213                                       Deacon, Mr. Percy William 0.23370898
## 214                    Howard, Mrs. Benjamin (Ellen Truelove Arman) 0.78709932
## 215                          Andersson, Miss. Ida Augusta Margareta 0.40714133
## 216                                           Head, Mr. Christopher 0.43818663
## 217                                      Mahon, Miss. Bridget Delia 0.64946522
## 218                                        Wick, Mr. George Dennick 0.37832918
## 219                    Widener, Mrs. George Dunton (Eleanor Elkins) 0.90434727
## 220                                 Thomson, Mr. Alexander Morrison 0.10655287
## 221                                  Duran y More, Miss. Florentina 0.78709932
## 222                                          Reynolds, Mr. Harold J 0.10655287
## 223                                      Cook, Mrs. (Selena Rogers) 0.82572825
## 224                                   Karlsson, Mr. Einar Gervasius 0.10655287
## 225                Candee, Mrs. Edward (Helen Churchill Hungerford) 0.92376313
## 226                Moubarek, Mrs. George (Omine Amenia&quot; Alexander)&quot; 0.64946522
## 227                                      Asplund, Mr. Johan Charles 0.10655287
## 228                                          McNeill, Miss. Bridget 0.64946522
## 229                                       Everett, Mr. Thomas James 0.10655287
## 230                              Hocking, Mr. Samuel James Metcalfe 0.23370898
## 231                                     Sweet, Mr. George Frederick 0.23370898
## 232                                        Willard, Miss. Constance 0.92376313
## 233                                         Wiklund, Mr. Karl Johan 0.08513275
## 234                                            Linehan, Mr. Michael 0.10655287
## 235                                       Cumings, Mr. John Bradley 0.37832918
## 236                                          Vendel, Mr. Olof Edvin 0.10655287
## 237                                        Warren, Mr. Frank Manley 0.37832918
## 238                                             Baccos, Mr. Raffull 0.10655287
## 239                                           Hiltunen, Miss. Marta 0.78709932
## 240                     Douglas, Mrs. Walter Donald (Mahala Dutton) 0.90434727
## 241                       Lindstrom, Mrs. Carl Johan (Sigrid Posse) 0.92376313
## 242                                   Christy, Mrs. (Alice Frances) 0.82572825
## 243                                    Spedden, Mr. Frederic Oakley 0.37832918
## 244                                              Hyman, Mr. Abraham 0.10655287
## 245                       Johnston, Master. William Arthur Willie&quot;&quot; 0.08513275
## 246                                         Kenyon, Mr. Frederick R 0.37832918
## 247                           Karnes, Mrs. J Frank (Claire Bennett) 0.82572825
## 248                                          Drew, Mr. James Vivian 0.19222661
## 249                        Hold, Mrs. Stephen (Annie Margaret Hill) 0.78709932
## 250                       Khalil, Mrs. Betros (Zahie Maria&quot; Elias)&quot; 0.59111294
## 251                                           West, Miss. Barbara J 0.78709932
## 252                        Abrahamsson, Mr. Abraham August Johannes 0.10655287
## 253                                        Clark, Mr. Walter Miller 0.37832918
## 254                                        Salander, Mr. Karl Johan 0.10655287
## 255                                             Wenzel, Mr. Linhart 0.10655287
## 256                                      MacKay, Mr. George William 0.10655287
## 257                                                 Mahon, Mr. John 0.10655287
## 258                                           Niklasson, Mr. Samuel 0.10655287
## 259                                         Bentham, Miss. Lilian W 0.82572825
## 260                                        Midtsjo, Mr. Karl Albert 0.10655287
## 261                            de Messemaeker, Mr. Guillaume Joseph 0.08513275
## 262                                   Nilsson, Mr. August Ferdinand 0.10655287
## 263               Wells, Mrs. Arthur Henry (Addie&quot; Dart Trevaskis)&quot; 0.82572825
## 264                                    Klasen, Miss. Gertrud Emilia 0.59111294
## 265                          Portaluppi, Mr. Emilio Ilario Giuseppe 0.23370898
## 266                                           Lyntakoff, Mr. Stanko 0.10655287
## 267                           Chisholm, Mr. Roderick Robert Crispin 0.43818663
## 268                                     Warren, Mr. Charles William 0.10655287
## 269                                     Howard, Miss. May Elizabeth 0.64946522
## 270                                               Pokrnic, Mr. Mate 0.10655287
## 271                                    McCaffry, Mr. Thomas Francis 0.43818663
## 272                                                Fox, Mr. Patrick 0.10655287
## 273                   Clark, Mrs. Walter Miller (Virginia McDowell) 0.90434727
## 274                                              Lennon, Miss. Mary 0.59111294
## 275                                           Saade, Mr. Jean Nassr 0.10655287
## 276                              Bryhl, Miss. Dagmar Jenny Ingeborg 0.78709932
## 277                                    Parker, Mr. Clifford Richard 0.23370898
## 278                                           Faunthorpe, Mr. Harry 0.19222661
## 279                                            Ware, Mr. John James 0.19222661
## 280                                       Oxenham, Mr. Percy Thomas 0.23370898
## 281                                          Oreskovic, Miss. Jelka 0.64946522
## 282                                  Peacock, Master. Alfred Edward 0.08513275
## 283                                           Fleming, Miss. Honora 0.64946522
## 284                                      Touma, Miss. Maria Youssef 0.59111294
## 285                                     Rosblom, Miss. Salli Helena 0.59111294
## 286                                             Dennis, Mr. William 0.10655287
## 287                          Franklin, Mr. Charles (Charles Fardon) 0.10655287
## 288                                      Snyder, Mr. John Pillsbury 0.37832918
## 289                                         Mardirosian, Mr. Sarkis 0.10655287
## 290                                                Ford, Mr. Arthur 0.10655287
## 291                             Rheims, Mr. George Alexander Lucien 0.43818663
## 292                          Daly, Miss. Margaret Marcella Maggie&quot;&quot; 0.64946522
## 293                                               Nasr, Mr. Mustafa 0.10655287
## 294                                           Dodge, Dr. Washington 0.37832918
## 295                                       Wittevrongel, Mr. Camille 0.10655287
## 296                                            Angheloff, Mr. Minko 0.10655287
## 297                                           Laroche, Miss. Louise 0.78709932
## 298                                               Samaan, Mr. Hanna 0.06769243
## 299                                      Loring, Mr. Joseph Holland 0.43818663
## 300                                             Johansson, Mr. Nils 0.10655287
## 301                                       Olsson, Mr. Oscar Wilhelm 0.10655287
## 302                                             Malachard, Mr. Noel 0.23370898
## 303                                     Phillips, Mr. Escott Robert 0.23370898
## 304                                               Pokrnic, Mr. Tome 0.10655287
## 305                               McCarthy, Miss. Catherine Katie&quot;&quot; 0.64946522
## 306      Crosby, Mrs. Edward Gifford (Catherine Elizabeth Halstead) 0.90434727
## 307                            Allison, Mr. Hudson Joshua Creighton 0.37832918
## 308                                       Aks, Master. Philip Frank 0.10655287
## 309                                      Hays, Mr. Charles Melville 0.37832918
## 310                      Hansen, Mrs. Claus Peter (Jennie L Howard) 0.59111294
## 311                                            Cacic, Mr. Jego Grga 0.10655287
## 312                                            Vartanian, Mr. David 0.10655287
## 313                                             Sadowitz, Mr. Harry 0.10655287
## 314                                             Carr, Miss. Jeannie 0.64946522
## 315                           White, Mrs. John Stuart (Ella Holmes) 0.92376313
## 316                                            Hagardon, Miss. Kate 0.64946522
## 317                                   Spencer, Mr. William Augustus 0.37832918
## 318                                      Rogers, Mr. Reginald Harry 0.23370898
## 319                                       Jonsson, Mr. Nils Hilding 0.10655287
## 320                                    Jefferys, Mr. Ernest Wilfred 0.15660247
## 321                                     Andersson, Mr. Johan Samuel 0.10655287
## 322                                           Krekorian, Mr. Neshan 0.10655287
## 323                                              Nesson, Mr. Israel 0.23370898
## 324                                              Rowe, Mr. Alfred G 0.43818663
## 325                                          Kreuchen, Miss. Emilie 0.92376313
## 326                                                  Assam, Mr. Ali 0.10655287
## 327                                    Becker, Miss. Ruth Elizabeth 0.74257728
## 328                     Rosenshine, Mr. George (Mr George Thorne&quot;)&quot; 0.43818663
## 329                                   Clarke, Mr. Charles Valentine 0.19222661
## 330                                             Enander, Mr. Ingvar 0.23370898
## 331           Davies, Mrs. John Morgan (Elizabeth Agnes Mary White) 0.82572825
## 332                                    Dulles, Mr. William Crothers 0.43818663
## 333                                             Thomas, Mr. Tannous 0.10655287
## 334                           Nakid, Mrs. Said (Waika Mary&quot; Mowad)&quot; 0.59111294
## 335                                                   Cor, Mr. Ivan 0.10655287
## 336                                        Maguire, Mr. John Edward 0.43818663
## 337                                      de Brito, Mr. Jose Joaquim 0.23370898
## 338                                               Elias, Mr. Joseph 0.10655287
## 339                                            Denbury, Mr. Herbert 0.23370898
## 340                                           Betros, Master. Seman 0.10655287
## 341                                   Fillbrook, Mr. Joseph Charles 0.23370898
## 342                                      Lundstrom, Mr. Thure Edvin 0.10655287
## 343                                           Sage, Mr. John George 0.08513275
## 344 Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake) 0.92376313
## 345                             van Billiard, Master. James William 0.08513275
## 346                                     Abelseth, Miss. Karen Marie 0.64946522
## 347                                      Botsford, Mr. William Hull 0.23370898
## 348                 Whabee, Mrs. George Joseph (Shawneene Abi-Saab) 0.64946522
## 349                                                Giles, Mr. Ralph 0.23370898
## 350                                          Walcroft, Miss. Nellie 0.82572825
## 351                    Greenfield, Mrs. Leo David (Blanche Strouse) 0.92376313
## 352                                       Stokes, Mr. Philip Joseph 0.23370898
## 353                                             Dibden, Mr. William 0.23370898
## 354                                              Herman, Mr. Samuel 0.19222661
## 355                         Dean, Miss. Elizabeth Gladys Millvina&quot;&quot; 0.59111294
## 356                                        Julian, Mr. Henry Forbes 0.43818663
## 357                  Brown, Mrs. John Murray (Caroline Lane Lamson) 0.88062562
## 358                                             Lockyer, Mr. Edward 0.10655287
## 359                                            O&#39;Keefe, Mr. Patrick 0.10655287
## 360             Lindell, Mrs. Edvard Bengtsson (Elin Gerda Persson) 0.59111294
## 361                                     Sage, Master. William Henry 0.01612043
## 362                         Mallet, Mrs. Albert (Antoinette Magnin) 0.78709932
## 363                    Ware, Mrs. John James (Florence Louise Long) 0.82572825
## 364                                               Strilic, Mr. Ivan 0.10655287
## 365                    Harder, Mrs. George Achilles (Dorothy Annan) 0.90434727
## 366                                  Sage, Mrs. John (Annie Bullen) 0.59111294
## 367                                               Caram, Mr. Joseph 0.08513275
## 368                    Riihivouri, Miss. Susanna Juhantytar Sanni&quot;&quot; 0.64946522
## 369                         Gibson, Mrs. Leonard (Pauline C Boeson) 0.92376313
## 370                                   Pallas y Castello, Mr. Emilio 0.23370898
## 371                                                Giles, Mr. Edgar 0.19222661
## 372                                       Wilson, Miss. Helen Alice 0.92376313
## 373                                         Ismay, Mr. Joseph Bruce 0.43818663
## 374                                          Harbeck, Mr. William H 0.23370898
## 375                           Dodge, Mrs. Washington (Ruth Vidaver) 0.90434727
## 376                                        Bowen, Miss. Grace Scott 0.92376313
## 377                                               Kink, Miss. Maria 0.53007536
## 378                                    Cotterill, Mr. Henry Harry&quot;&quot; 0.23370898
## 379                                     Hipkins, Mr. William Edward 0.43818663
## 380                                     Asplund, Master. Carl Edgar 0.04233309
## 381                                           O&#39;Connor, Mr. Patrick 0.10655287
## 382                                               Foley, Mr. Joseph 0.10655287
## 383                                      Risien, Mrs. Samuel (Emma) 0.64946522
## 384                             McNamee, Mrs. Neal (Eileen O&#39;Leary) 0.59111294
## 385                                  Wheeler, Mr. Edwin Frederick&quot;&quot; 0.23370898
## 386                                              Herman, Miss. Kate 0.78709932
## 387                                  Aronsson, Mr. Ernst Axel Algot 0.10655287
## 388                                                 Ashby, Mr. John 0.23370898
## 389                                            Canavan, Mr. Patrick 0.10655287
## 390                                     Palsson, Master. Paul Folke 0.05361555
## 391                                      Payne, Mr. Vivian Ponsonby 0.43818663
## 392                  Lines, Mrs. Ernest H (Elizabeth Lindsey James) 0.92376313
## 393                                   Abbott, Master. Eugene Joseph 0.10655287
## 394                                            Gilbert, Mr. William 0.23370898
## 395                                        Kink-Heilmann, Mr. Anton 0.05361555
## 396                  Smith, Mrs. Lucien Philip (Mary Eloise Hughes) 0.90434727
## 397                                            Colbert, Mr. Patrick 0.10655287
## 398 Frolicher-Stehli, Mrs. Maxmillian (Margaretha Emerentia Stehli) 0.90434727
## 399                                  Larsson-Rondberg, Mr. Edvard A 0.10655287
## 400                                        Conlon, Mr. Thomas Henry 0.10655287
## 401                                         Bonnell, Miss. Caroline 0.92376313
## 402                                                 Gale, Mr. Harry 0.19222661
## 403                                  Gibson, Miss. Dorothy Winifred 0.92376313
## 404                                          Carrau, Mr. Jose Pedro 0.43818663
## 405                                    Frauenthal, Mr. Isaac Gerald 0.37832918
## 406                    Nourney, Mr. Alfred (Baron von Drachstedt&quot;)&quot; 0.23370898
## 407                                       Ware, Mr. William Jeffery 0.19222661
## 408                                      Widener, Mr. George Dunton 0.37832918
## 409                                 Riordan, Miss. Johanna Hannah&quot;&quot; 0.64946522
## 410                                       Peacock, Miss. Treasteall 0.59111294
## 411                                          Naughton, Miss. Hannah 0.64946522
## 412                 Minahan, Mrs. William Edward (Lillian E Thorpe) 0.90434727
## 413                                  Henriksson, Miss. Jenny Lovisa 0.64946522
## 414                                              Spector, Mr. Woolf 0.10655287
## 415                                    Oliva y Ocana, Dona. Fermina 0.92376313
## 416                                    Saether, Mr. Simon Sivertsen 0.10655287
## 417                                             Ware, Mr. Frederick 0.10655287
## 418                                        Peter, Master. Michael J 0.08513275</code></pre>
</div>
<div id="we-can-see-the-survival-probability-for-each-of-the-passengers-along-with-their-name-and-passenger-id." class="section level3">
<h3>We can see the survival probability for each of the passengers along with their name and passenger ID.</h3>
</div>
<div id="however-having-the-probablity-of-surviving-is-not-very-useful-on-its-own.-the-power-of-a-logistic-model-is-to-determine-a-binary-output-which-in-this-case-if-the-passenger-survives.-therefore-we-run-a-command-that-converts-all-probability-of-surviving-below-50-to-not-survived-or-a-0-and-all-probabilities-above-to-survived-or-a-1." class="section level3">
<h3>However, having the probablity of surviving is not very useful on its own. The power of a logistic model is to determine a binary output which in this case if the passenger survives. Therefore, we run a command that converts all probability of surviving below 50% to not survived or a 0, and all probabilities above to survived or a 1.</h3>
<pre class="r"><code>output$Survived = ifelse(output$Survived &gt; 0.5, 1, 0)
output</code></pre>
<pre><code>##     test.PassengerId
## 1                892
## 2                893
## 3                894
## 4                895
## 5                896
## 6                897
## 7                898
## 8                899
## 9                900
## 10               901
## 11               902
## 12               903
## 13               904
## 14               905
## 15               906
## 16               907
## 17               908
## 18               909
## 19               910
## 20               911
## 21               912
## 22               913
## 23               914
## 24               915
## 25               916
## 26               917
## 27               918
## 28               919
## 29               920
## 30               921
## 31               922
## 32               923
## 33               924
## 34               925
## 35               926
## 36               927
## 37               928
## 38               929
## 39               930
## 40               931
## 41               932
## 42               933
## 43               934
## 44               935
## 45               936
## 46               937
## 47               938
## 48               939
## 49               940
## 50               941
## 51               942
## 52               943
## 53               944
## 54               945
## 55               946
## 56               947
## 57               948
## 58               949
## 59               950
## 60               951
## 61               952
## 62               953
## 63               954
## 64               955
## 65               956
## 66               957
## 67               958
## 68               959
## 69               960
## 70               961
## 71               962
## 72               963
## 73               964
## 74               965
## 75               966
## 76               967
## 77               968
## 78               969
## 79               970
## 80               971
## 81               972
## 82               973
## 83               974
## 84               975
## 85               976
## 86               977
## 87               978
## 88               979
## 89               980
## 90               981
## 91               982
## 92               983
## 93               984
## 94               985
## 95               986
## 96               987
## 97               988
## 98               989
## 99               990
## 100              991
## 101              992
## 102              993
## 103              994
## 104              995
## 105              996
## 106              997
## 107              998
## 108              999
## 109             1000
## 110             1001
## 111             1002
## 112             1003
## 113             1004
## 114             1005
## 115             1006
## 116             1007
## 117             1008
## 118             1009
## 119             1010
## 120             1011
## 121             1012
## 122             1013
## 123             1014
## 124             1015
## 125             1016
## 126             1017
## 127             1018
## 128             1019
## 129             1020
## 130             1021
## 131             1022
## 132             1023
## 133             1024
## 134             1025
## 135             1026
## 136             1027
## 137             1028
## 138             1029
## 139             1030
## 140             1031
## 141             1032
## 142             1033
## 143             1034
## 144             1035
## 145             1036
## 146             1037
## 147             1038
## 148             1039
## 149             1040
## 150             1041
## 151             1042
## 152             1043
## 153             1044
## 154             1045
## 155             1046
## 156             1047
## 157             1048
## 158             1049
## 159             1050
## 160             1051
## 161             1052
## 162             1053
## 163             1054
## 164             1055
## 165             1056
## 166             1057
## 167             1058
## 168             1059
## 169             1060
## 170             1061
## 171             1062
## 172             1063
## 173             1064
## 174             1065
## 175             1066
## 176             1067
## 177             1068
## 178             1069
## 179             1070
## 180             1071
## 181             1072
## 182             1073
## 183             1074
## 184             1075
## 185             1076
## 186             1077
## 187             1078
## 188             1079
## 189             1080
## 190             1081
## 191             1082
## 192             1083
## 193             1084
## 194             1085
## 195             1086
## 196             1087
## 197             1088
## 198             1089
## 199             1090
## 200             1091
## 201             1092
## 202             1093
## 203             1094
## 204             1095
## 205             1096
## 206             1097
## 207             1098
## 208             1099
## 209             1100
## 210             1101
## 211             1102
## 212             1103
## 213             1104
## 214             1105
## 215             1106
## 216             1107
## 217             1108
## 218             1109
## 219             1110
## 220             1111
## 221             1112
## 222             1113
## 223             1114
## 224             1115
## 225             1116
## 226             1117
## 227             1118
## 228             1119
## 229             1120
## 230             1121
## 231             1122
## 232             1123
## 233             1124
## 234             1125
## 235             1126
## 236             1127
## 237             1128
## 238             1129
## 239             1130
## 240             1131
## 241             1132
## 242             1133
## 243             1134
## 244             1135
## 245             1136
## 246             1137
## 247             1138
## 248             1139
## 249             1140
## 250             1141
## 251             1142
## 252             1143
## 253             1144
## 254             1145
## 255             1146
## 256             1147
## 257             1148
## 258             1149
## 259             1150
## 260             1151
## 261             1152
## 262             1153
## 263             1154
## 264             1155
## 265             1156
## 266             1157
## 267             1158
## 268             1159
## 269             1160
## 270             1161
## 271             1162
## 272             1163
## 273             1164
## 274             1165
## 275             1166
## 276             1167
## 277             1168
## 278             1169
## 279             1170
## 280             1171
## 281             1172
## 282             1173
## 283             1174
## 284             1175
## 285             1176
## 286             1177
## 287             1178
## 288             1179
## 289             1180
## 290             1181
## 291             1182
## 292             1183
## 293             1184
## 294             1185
## 295             1186
## 296             1187
## 297             1188
## 298             1189
## 299             1190
## 300             1191
## 301             1192
## 302             1193
## 303             1194
## 304             1195
## 305             1196
## 306             1197
## 307             1198
## 308             1199
## 309             1200
## 310             1201
## 311             1202
## 312             1203
## 313             1204
## 314             1205
## 315             1206
## 316             1207
## 317             1208
## 318             1209
## 319             1210
## 320             1211
## 321             1212
## 322             1213
## 323             1214
## 324             1215
## 325             1216
## 326             1217
## 327             1218
## 328             1219
## 329             1220
## 330             1221
## 331             1222
## 332             1223
## 333             1224
## 334             1225
## 335             1226
## 336             1227
## 337             1228
## 338             1229
## 339             1230
## 340             1231
## 341             1232
## 342             1233
## 343             1234
## 344             1235
## 345             1236
## 346             1237
## 347             1238
## 348             1239
## 349             1240
## 350             1241
## 351             1242
## 352             1243
## 353             1244
## 354             1245
## 355             1246
## 356             1247
## 357             1248
## 358             1249
## 359             1250
## 360             1251
## 361             1252
## 362             1253
## 363             1254
## 364             1255
## 365             1256
## 366             1257
## 367             1258
## 368             1259
## 369             1260
## 370             1261
## 371             1262
## 372             1263
## 373             1264
## 374             1265
## 375             1266
## 376             1267
## 377             1268
## 378             1269
## 379             1270
## 380             1271
## 381             1272
## 382             1273
## 383             1274
## 384             1275
## 385             1276
## 386             1277
## 387             1278
## 388             1279
## 389             1280
## 390             1281
## 391             1282
## 392             1283
## 393             1284
## 394             1285
## 395             1286
## 396             1287
## 397             1288
## 398             1289
## 399             1290
## 400             1291
## 401             1292
## 402             1293
## 403             1294
## 404             1295
## 405             1296
## 406             1297
## 407             1298
## 408             1299
## 409             1300
## 410             1301
## 411             1302
## 412             1303
## 413             1304
## 414             1305
## 415             1306
## 416             1307
## 417             1308
## 418             1309
##                                                           test.Name Survived
## 1                                                  Kelly, Mr. James        0
## 2                                  Wilkes, Mrs. James (Ellen Needs)        1
## 3                                         Myles, Mr. Thomas Francis        0
## 4                                                  Wirz, Mr. Albert        0
## 5                      Hirvonen, Mrs. Alexander (Helga E Lindqvist)        1
## 6                                        Svensson, Mr. Johan Cervin        0
## 7                                              Connolly, Miss. Kate        1
## 8                                      Caldwell, Mr. Albert Francis        0
## 9                         Abrahim, Mrs. Joseph (Sophie Halaut Easu)        1
## 10                                          Davies, Mr. John Samuel        0
## 11                                                 Ilieff, Mr. Ylio        0
## 12                                       Jones, Mr. Charles Cresson        0
## 13                    Snyder, Mrs. John Pillsbury (Nelle Stevenson)        1
## 14                                             Howard, Mr. Benjamin        0
## 15          Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)        1
## 16                    del Carlo, Mrs. Sebastiano (Argenia Genovesi)        1
## 17                                                Keane, Mr. Daniel        0
## 18                                                Assaf, Mr. Gerios        0
## 19                                     Ilmakangas, Miss. Ida Livija        1
## 20                            Assaf Khalil, Mrs. Mariana (Miriam&quot;)&quot;        1
## 21                                           Rothschild, Mr. Martin        0
## 22                                        Olsen, Master. Artur Karl        0
## 23                             Flegenheim, Mrs. Alfred (Antoinette)        1
## 24                                  Williams, Mr. Richard Norris II        0
## 25                  Ryerson, Mrs. Arthur Larned (Emily Maria Borie)        1
## 26                                          Robins, Mr. Alexander A        0
## 27                                     Ostby, Miss. Helene Ragnhild        1
## 28                                                Daher, Mr. Shedid        0
## 29                                          Brady, Mr. John Bertram        0
## 30                                                Samaan, Mr. Elias        0
## 31                                     Louch, Mr. Charles Alexander        0
## 32                                    Jefferys, Mr. Clifford Thomas        0
## 33                         Dean, Mrs. Bertram (Eva Georgetta Light)        1
## 34                Johnston, Mrs. Andrew G (Elizabeth Lily&quot; Watson)&quot;        1
## 35                                         Mock, Mr. Philipp Edmund        0
## 36                 Katavelas, Mr. Vassilios (Catavelas Vassilios&quot;)&quot;        0
## 37                                              Roth, Miss. Sarah A        1
## 38                                               Cacic, Miss. Manda        1
## 39                                                  Sap, Mr. Julius        0
## 40                                                    Hee, Mr. Ling        0
## 41                                                 Karun, Mr. Franz        0
## 42                                      Franklin, Mr. Thomas Parham        0
## 43                                            Goldsmith, Mr. Nathan        0
## 44                            Corbett, Mrs. Walter H (Irene Colvin)        1
## 45                 Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)        1
## 46                                  Peltomaki, Mr. Nikolai Johannes        0
## 47                                         Chevre, Mr. Paul Romaine        0
## 48                                         Shaughnessy, Mr. Patrick        0
## 49                  Bucknell, Mrs. William Robert (Emma Eliza Ward)        1
## 50                   Coutts, Mrs. William (Winnie Minnie&quot; Treanor)&quot;        1
## 51                                         Smith, Mr. Lucien Philip        0
## 52                                               Pulbaum, Mr. Franz        0
## 53                                    Hocking, Miss. Ellen Nellie&quot;&quot;        1
## 54                                       Fortune, Miss. Ethel Flora        1
## 55                                Mangiavacchi, Mr. Serafino Emilio        0
## 56                                             Rice, Master. Albert        0
## 57                                                  Cor, Mr. Bartol        0
## 58                                    Abelseth, Mr. Olaus Jorgensen        0
## 59                                        Davison, Mr. Thomas Henry        0
## 60                                      Chaudanson, Miss. Victorine        1
## 61                                                  Dika, Mr. Mirko        0
## 62                                        McCrae, Mr. Arthur Gordon        0
## 63                                     Bjorklund, Mr. Ernst Herbert        0
## 64                                     Bradley, Miss. Bridget Delia        1
## 65                                      Ryerson, Master. John Borie        0
## 66              Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller)        1
## 67                                          Burns, Miss. Mary Delia        1
## 68                                   Moore, Mr. Clarence Bloomfield        0
## 69                                  Tucker, Mr. Gilbert Milligan Jr        0
## 70                              Fortune, Mrs. Mark (Mary McDougald)        1
## 71                                        Mulvihill, Miss. Bertha E        1
## 72                                               Minkoff, Mr. Lazar        0
## 73                                   Nieminen, Miss. Manta Josefina        1
## 74                                  Ovies y Rodriguez, Mr. Servando        0
## 75                                             Geiger, Miss. Amalie        1
## 76                                               Keeping, Mr. Edwin        0
## 77                                                 Miles, Mr. Frank        0
## 78             Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)        1
## 79                                   Aldworth, Mr. Charles Augustus        0
## 80                                           Doyle, Miss. Elizabeth        1
## 81                                             Boulos, Master. Akar        0
## 82                                               Straus, Mr. Isidor        0
## 83                                           Case, Mr. Howard Brown        0
## 84                                             Demetri, Mr. Marinko        0
## 85                                            Lamb, Mr. John Joseph        0
## 86                                               Khalil, Mr. Betros        0
## 87                                               Barry, Miss. Julia        1
## 88                                       Badman, Miss. Emily Louisa        1
## 89                                          O&#39;Donoghue, Ms. Bridget        1
## 90                                      Wells, Master. Ralph Lester        0
## 91      Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judith Andersson)        1
## 92                                               Pedersen, Mr. Olaf        0
## 93                             Davidson, Mrs. Thornton (Orian Hays)        1
## 94                                                Guest, Mr. Robert        0
## 95                                              Birnbaum, Mr. Jakob        0
## 96                                       Tenglin, Mr. Gunnar Isidor        0
## 97           Cavendish, Mrs. Tyrell William (Julia Florence Siegel)        1
## 98                                        Makinen, Mr. Kalle Edvard        0
## 99                                     Braf, Miss. Elin Ester Maria        1
## 100                                    Nancarrow, Mr. William Henry        0
## 101             Stengel, Mrs. Charles Emil Henry (Annie May Morris)        1
## 102                                              Weisz, Mr. Leopold        0
## 103                                              Foley, Mr. William        0
## 104                          Johansson Palmquist, Mr. Oskar Leander        0
## 105                       Thomas, Mrs. Alexander (Thamine Thelma&quot;)&quot;        1
## 106                                       Holthen, Mr. Johan Martin        0
## 107                                             Buckley, Mr. Daniel        0
## 108                                                Ryan, Mr. Edward        0
## 109                                Willer, Mr. Aaron (Abi Weller&quot;)&quot;        0
## 110                                               Swane, Mr. George        0
## 111                                        Stanton, Mr. Samuel Ward        0
## 112                                      Shine, Miss. Ellen Natalia        1
## 113                                        Evans, Miss. Edith Corse        1
## 114                                        Buckley, Miss. Katherine        1
## 115                          Straus, Mrs. Isidor (Rosalie Ida Blun)        1
## 116                                     Chronopoulos, Mr. Demetrios        0
## 117                                                Thomas, Mr. John        0
## 118                                 Sandstrom, Miss. Beatrice Irene        1
## 119                                            Beattie, Mr. Thomson        0
## 120                 Chapman, Mrs. John Henry (Sara Elizabeth Lawry)        1
## 121                                            Watt, Miss. Bertha J        1
## 122                                               Kiernan, Mr. John        0
## 123                                 Schabert, Mrs. Paul (Emma Mock)        1
## 124                                         Carver, Mr. Alfred John        0
## 125                                               Kennedy, Mr. John        0
## 126                                        Cribb, Miss. Laura Alice        1
## 127                                        Brobeck, Mr. Karl Rudolf        0
## 128                                             McCoy, Miss. Alicia        1
## 129                                            Bowenur, Mr. Solomon        0
## 130                                            Petersen, Mr. Marius        0
## 131                                         Spinner, Mr. Henry John        0
## 132                                       Gracie, Col. Archibald IV        0
## 133                                   Lefebre, Mrs. Frank (Frances)        1
## 134                                           Thomas, Mr. Charles P        0
## 135                                          Dintcheff, Mr. Valtcho        0
## 136                                       Carlsson, Mr. Carl Robert        0
## 137                                       Zakarian, Mr. Mapriededer        0
## 138                                             Schmidt, Mr. August        0
## 139                                           Drapkin, Miss. Jennie        1
## 140                                  Goodwin, Mr. Charles Frederick        0
## 141                                     Goodwin, Miss. Jessie Allis        0
## 142                                            Daniels, Miss. Sarah        1
## 143                                      Ryerson, Mr. Arthur Larned        0
## 144                                      Beauchamp, Mr. Henry James        0
## 145           Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lingrey&quot;)&quot;        0
## 146                                       Vander Planke, Mr. Julius        0
## 147                                     Hilliard, Mr. Herbert Henry        0
## 148                                                Davies, Mr. Evan        0
## 149                                       Crafton, Mr. John Bertram        0
## 150                                          Lahtinen, Rev. William        0
## 151                           Earnshaw, Mrs. Boulton (Olive Potter)        1
## 152                                            Matinoff, Mr. Nicola        0
## 153                                              Storey, Mr. Thomas        0
## 154                  Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)        1
## 155                                    Asplund, Master. Filip Oscar        0
## 156                                            Duquemin, Mr. Joseph        0
## 157                                               Bird, Miss. Ellen        1
## 158                                        Lundin, Miss. Olga Elida        1
## 159                                        Borebank, Mr. John James        0
## 160                             Peacock, Mrs. Benjamin (Edith Nile)        1
## 161                                              Smyth, Miss. Julia        1
## 162                                  Touma, Master. Georges Youssef        0
## 163                                            Wright, Miss. Marion        1
## 164                                              Pearce, Mr. Ernest        0
## 165                                   Peruschitz, Rev. Joseph Maria        0
## 166                      Kink-Heilmann, Mrs. Anton (Luise Heilmann)        1
## 167                                              Brandeis, Mr. Emil        0
## 168                                         Ford, Mr. Edward Watson        0
## 169     Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)        1
## 170                                    Hellstrom, Miss. Hilda Maria        1
## 171                                              Lithman, Mr. Simon        0
## 172                                             Zakarian, Mr. Ortin        0
## 173                                        Dyker, Mr. Adolf Fredrik        0
## 174                                                Torfa, Mr. Assad        0
## 175                      Asplund, Mr. Carl Oscar Vilhelm Gustafsson        0
## 176                                       Brown, Miss. Edith Eileen        1
## 177                                            Sincock, Miss. Maude        1
## 178                                 Stengel, Mr. Charles Emil Henry        0
## 179                Becker, Mrs. Allen Oliver (Nellie E Baumgardner)        1
## 180           Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)        1
## 181                                       McCrie, Mr. James Matthew        0
## 182                                Compton, Mr. Alexander Taylor Jr        0
## 183  Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)        1
## 184                                               Lane, Mr. Patrick        0
## 185            Douglas, Mrs. Frederick Charles (Mary Helene Baxter)        1
## 186                                       Maybery, Mr. Frank Hubert        0
## 187                            Phillips, Miss. Alice Frances Louisa        1
## 188                                              Davies, Mr. Joseph        0
## 189                                                 Sage, Miss. Ada        0
## 190                                                 Veal, Mr. James        0
## 191                                            Angle, Mr. William A        0
## 192                                          Salomon, Mr. Abraham L        0
## 193                               van Billiard, Master. Walter John        0
## 194                                               Lingane, Mr. John        0
## 195                                   Drew, Master. Marshall Brines        0
## 196                               Karlsson, Mr. Julius Konrad Eugen        0
## 197                                 Spedden, Master. Robert Douglas        0
## 198                                     Nilsson, Miss. Berta Olivia        1
## 199                                  Baimbrigge, Mr. Charles Robert        0
## 200                         Rasmussen, Mrs. (Lena Jacobsen Solvang)        1
## 201                                              Murphy, Miss. Nora        1
## 202                         Danbom, Master. Gilbert Sigvard Emanuel        0
## 203                                          Astor, Col. John Jacob        0
## 204                                      Quick, Miss. Winifred Vera        1
## 205                                        Andrew, Mr. Frank Thomas        0
## 206                                       Omont, Mr. Alfred Fernand        0
## 207                                        McGowan, Miss. Katherine        1
## 208                                    Collett, Mr. Sidney C Stuart        0
## 209                                   Rosenbaum, Miss. Edith Louise        1
## 210                                              Delalic, Mr. Redjo        0
## 211                                     Andersen, Mr. Albert Karvin        0
## 212                                               Finoli, Mr. Luigi        0
## 213                                       Deacon, Mr. Percy William        0
## 214                    Howard, Mrs. Benjamin (Ellen Truelove Arman)        1
## 215                          Andersson, Miss. Ida Augusta Margareta        0
## 216                                           Head, Mr. Christopher        0
## 217                                      Mahon, Miss. Bridget Delia        1
## 218                                        Wick, Mr. George Dennick        0
## 219                    Widener, Mrs. George Dunton (Eleanor Elkins)        1
## 220                                 Thomson, Mr. Alexander Morrison        0
## 221                                  Duran y More, Miss. Florentina        1
## 222                                          Reynolds, Mr. Harold J        0
## 223                                      Cook, Mrs. (Selena Rogers)        1
## 224                                   Karlsson, Mr. Einar Gervasius        0
## 225                Candee, Mrs. Edward (Helen Churchill Hungerford)        1
## 226                Moubarek, Mrs. George (Omine Amenia&quot; Alexander)&quot;        1
## 227                                      Asplund, Mr. Johan Charles        0
## 228                                          McNeill, Miss. Bridget        1
## 229                                       Everett, Mr. Thomas James        0
## 230                              Hocking, Mr. Samuel James Metcalfe        0
## 231                                     Sweet, Mr. George Frederick        0
## 232                                        Willard, Miss. Constance        1
## 233                                         Wiklund, Mr. Karl Johan        0
## 234                                            Linehan, Mr. Michael        0
## 235                                       Cumings, Mr. John Bradley        0
## 236                                          Vendel, Mr. Olof Edvin        0
## 237                                        Warren, Mr. Frank Manley        0
## 238                                             Baccos, Mr. Raffull        0
## 239                                           Hiltunen, Miss. Marta        1
## 240                     Douglas, Mrs. Walter Donald (Mahala Dutton)        1
## 241                       Lindstrom, Mrs. Carl Johan (Sigrid Posse)        1
## 242                                   Christy, Mrs. (Alice Frances)        1
## 243                                    Spedden, Mr. Frederic Oakley        0
## 244                                              Hyman, Mr. Abraham        0
## 245                       Johnston, Master. William Arthur Willie&quot;&quot;        0
## 246                                         Kenyon, Mr. Frederick R        0
## 247                           Karnes, Mrs. J Frank (Claire Bennett)        1
## 248                                          Drew, Mr. James Vivian        0
## 249                        Hold, Mrs. Stephen (Annie Margaret Hill)        1
## 250                       Khalil, Mrs. Betros (Zahie Maria&quot; Elias)&quot;        1
## 251                                           West, Miss. Barbara J        1
## 252                        Abrahamsson, Mr. Abraham August Johannes        0
## 253                                        Clark, Mr. Walter Miller        0
## 254                                        Salander, Mr. Karl Johan        0
## 255                                             Wenzel, Mr. Linhart        0
## 256                                      MacKay, Mr. George William        0
## 257                                                 Mahon, Mr. John        0
## 258                                           Niklasson, Mr. Samuel        0
## 259                                         Bentham, Miss. Lilian W        1
## 260                                        Midtsjo, Mr. Karl Albert        0
## 261                            de Messemaeker, Mr. Guillaume Joseph        0
## 262                                   Nilsson, Mr. August Ferdinand        0
## 263               Wells, Mrs. Arthur Henry (Addie&quot; Dart Trevaskis)&quot;        1
## 264                                    Klasen, Miss. Gertrud Emilia        1
## 265                          Portaluppi, Mr. Emilio Ilario Giuseppe        0
## 266                                           Lyntakoff, Mr. Stanko        0
## 267                           Chisholm, Mr. Roderick Robert Crispin        0
## 268                                     Warren, Mr. Charles William        0
## 269                                     Howard, Miss. May Elizabeth        1
## 270                                               Pokrnic, Mr. Mate        0
## 271                                    McCaffry, Mr. Thomas Francis        0
## 272                                                Fox, Mr. Patrick        0
## 273                   Clark, Mrs. Walter Miller (Virginia McDowell)        1
## 274                                              Lennon, Miss. Mary        1
## 275                                           Saade, Mr. Jean Nassr        0
## 276                              Bryhl, Miss. Dagmar Jenny Ingeborg        1
## 277                                    Parker, Mr. Clifford Richard        0
## 278                                           Faunthorpe, Mr. Harry        0
## 279                                            Ware, Mr. John James        0
## 280                                       Oxenham, Mr. Percy Thomas        0
## 281                                          Oreskovic, Miss. Jelka        1
## 282                                  Peacock, Master. Alfred Edward        0
## 283                                           Fleming, Miss. Honora        1
## 284                                      Touma, Miss. Maria Youssef        1
## 285                                     Rosblom, Miss. Salli Helena        1
## 286                                             Dennis, Mr. William        0
## 287                          Franklin, Mr. Charles (Charles Fardon)        0
## 288                                      Snyder, Mr. John Pillsbury        0
## 289                                         Mardirosian, Mr. Sarkis        0
## 290                                                Ford, Mr. Arthur        0
## 291                             Rheims, Mr. George Alexander Lucien        0
## 292                          Daly, Miss. Margaret Marcella Maggie&quot;&quot;        1
## 293                                               Nasr, Mr. Mustafa        0
## 294                                           Dodge, Dr. Washington        0
## 295                                       Wittevrongel, Mr. Camille        0
## 296                                            Angheloff, Mr. Minko        0
## 297                                           Laroche, Miss. Louise        1
## 298                                               Samaan, Mr. Hanna        0
## 299                                      Loring, Mr. Joseph Holland        0
## 300                                             Johansson, Mr. Nils        0
## 301                                       Olsson, Mr. Oscar Wilhelm        0
## 302                                             Malachard, Mr. Noel        0
## 303                                     Phillips, Mr. Escott Robert        0
## 304                                               Pokrnic, Mr. Tome        0
## 305                               McCarthy, Miss. Catherine Katie&quot;&quot;        1
## 306      Crosby, Mrs. Edward Gifford (Catherine Elizabeth Halstead)        1
## 307                            Allison, Mr. Hudson Joshua Creighton        0
## 308                                       Aks, Master. Philip Frank        0
## 309                                      Hays, Mr. Charles Melville        0
## 310                      Hansen, Mrs. Claus Peter (Jennie L Howard)        1
## 311                                            Cacic, Mr. Jego Grga        0
## 312                                            Vartanian, Mr. David        0
## 313                                             Sadowitz, Mr. Harry        0
## 314                                             Carr, Miss. Jeannie        1
## 315                           White, Mrs. John Stuart (Ella Holmes)        1
## 316                                            Hagardon, Miss. Kate        1
## 317                                   Spencer, Mr. William Augustus        0
## 318                                      Rogers, Mr. Reginald Harry        0
## 319                                       Jonsson, Mr. Nils Hilding        0
## 320                                    Jefferys, Mr. Ernest Wilfred        0
## 321                                     Andersson, Mr. Johan Samuel        0
## 322                                           Krekorian, Mr. Neshan        0
## 323                                              Nesson, Mr. Israel        0
## 324                                              Rowe, Mr. Alfred G        0
## 325                                          Kreuchen, Miss. Emilie        1
## 326                                                  Assam, Mr. Ali        0
## 327                                    Becker, Miss. Ruth Elizabeth        1
## 328                     Rosenshine, Mr. George (Mr George Thorne&quot;)&quot;        0
## 329                                   Clarke, Mr. Charles Valentine        0
## 330                                             Enander, Mr. Ingvar        0
## 331           Davies, Mrs. John Morgan (Elizabeth Agnes Mary White)        1
## 332                                    Dulles, Mr. William Crothers        0
## 333                                             Thomas, Mr. Tannous        0
## 334                           Nakid, Mrs. Said (Waika Mary&quot; Mowad)&quot;        1
## 335                                                   Cor, Mr. Ivan        0
## 336                                        Maguire, Mr. John Edward        0
## 337                                      de Brito, Mr. Jose Joaquim        0
## 338                                               Elias, Mr. Joseph        0
## 339                                            Denbury, Mr. Herbert        0
## 340                                           Betros, Master. Seman        0
## 341                                   Fillbrook, Mr. Joseph Charles        0
## 342                                      Lundstrom, Mr. Thure Edvin        0
## 343                                           Sage, Mr. John George        0
## 344 Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake)        1
## 345                             van Billiard, Master. James William        0
## 346                                     Abelseth, Miss. Karen Marie        1
## 347                                      Botsford, Mr. William Hull        0
## 348                 Whabee, Mrs. George Joseph (Shawneene Abi-Saab)        1
## 349                                                Giles, Mr. Ralph        0
## 350                                          Walcroft, Miss. Nellie        1
## 351                    Greenfield, Mrs. Leo David (Blanche Strouse)        1
## 352                                       Stokes, Mr. Philip Joseph        0
## 353                                             Dibden, Mr. William        0
## 354                                              Herman, Mr. Samuel        0
## 355                         Dean, Miss. Elizabeth Gladys Millvina&quot;&quot;        1
## 356                                        Julian, Mr. Henry Forbes        0
## 357                  Brown, Mrs. John Murray (Caroline Lane Lamson)        1
## 358                                             Lockyer, Mr. Edward        0
## 359                                            O&#39;Keefe, Mr. Patrick        0
## 360             Lindell, Mrs. Edvard Bengtsson (Elin Gerda Persson)        1
## 361                                     Sage, Master. William Henry        0
## 362                         Mallet, Mrs. Albert (Antoinette Magnin)        1
## 363                    Ware, Mrs. John James (Florence Louise Long)        1
## 364                                               Strilic, Mr. Ivan        0
## 365                    Harder, Mrs. George Achilles (Dorothy Annan)        1
## 366                                  Sage, Mrs. John (Annie Bullen)        1
## 367                                               Caram, Mr. Joseph        0
## 368                    Riihivouri, Miss. Susanna Juhantytar Sanni&quot;&quot;        1
## 369                         Gibson, Mrs. Leonard (Pauline C Boeson)        1
## 370                                   Pallas y Castello, Mr. Emilio        0
## 371                                                Giles, Mr. Edgar        0
## 372                                       Wilson, Miss. Helen Alice        1
## 373                                         Ismay, Mr. Joseph Bruce        0
## 374                                          Harbeck, Mr. William H        0
## 375                           Dodge, Mrs. Washington (Ruth Vidaver)        1
## 376                                        Bowen, Miss. Grace Scott        1
## 377                                               Kink, Miss. Maria        1
## 378                                    Cotterill, Mr. Henry Harry&quot;&quot;        0
## 379                                     Hipkins, Mr. William Edward        0
## 380                                     Asplund, Master. Carl Edgar        0
## 381                                           O&#39;Connor, Mr. Patrick        0
## 382                                               Foley, Mr. Joseph        0
## 383                                      Risien, Mrs. Samuel (Emma)        1
## 384                             McNamee, Mrs. Neal (Eileen O&#39;Leary)        1
## 385                                  Wheeler, Mr. Edwin Frederick&quot;&quot;        0
## 386                                              Herman, Miss. Kate        1
## 387                                  Aronsson, Mr. Ernst Axel Algot        0
## 388                                                 Ashby, Mr. John        0
## 389                                            Canavan, Mr. Patrick        0
## 390                                     Palsson, Master. Paul Folke        0
## 391                                      Payne, Mr. Vivian Ponsonby        0
## 392                  Lines, Mrs. Ernest H (Elizabeth Lindsey James)        1
## 393                                   Abbott, Master. Eugene Joseph        0
## 394                                            Gilbert, Mr. William        0
## 395                                        Kink-Heilmann, Mr. Anton        0
## 396                  Smith, Mrs. Lucien Philip (Mary Eloise Hughes)        1
## 397                                            Colbert, Mr. Patrick        0
## 398 Frolicher-Stehli, Mrs. Maxmillian (Margaretha Emerentia Stehli)        1
## 399                                  Larsson-Rondberg, Mr. Edvard A        0
## 400                                        Conlon, Mr. Thomas Henry        0
## 401                                         Bonnell, Miss. Caroline        1
## 402                                                 Gale, Mr. Harry        0
## 403                                  Gibson, Miss. Dorothy Winifred        1
## 404                                          Carrau, Mr. Jose Pedro        0
## 405                                    Frauenthal, Mr. Isaac Gerald        0
## 406                    Nourney, Mr. Alfred (Baron von Drachstedt&quot;)&quot;        0
## 407                                       Ware, Mr. William Jeffery        0
## 408                                      Widener, Mr. George Dunton        0
## 409                                 Riordan, Miss. Johanna Hannah&quot;&quot;        1
## 410                                       Peacock, Miss. Treasteall        1
## 411                                          Naughton, Miss. Hannah        1
## 412                 Minahan, Mrs. William Edward (Lillian E Thorpe)        1
## 413                                  Henriksson, Miss. Jenny Lovisa        1
## 414                                              Spector, Mr. Woolf        0
## 415                                    Oliva y Ocana, Dona. Fermina        1
## 416                                    Saether, Mr. Simon Sivertsen        0
## 417                                             Ware, Mr. Frederick        0
## 418                                        Peter, Master. Michael J        0</code></pre>
</div>
<div id="to-determine-the-power-of-our-model-we-can-compare-our-output-dataframe-against-the-submission-csv-file-generated-from-the-kaggle-python-script." class="section level3">
<h3>To determine, the power of our model we can compare our output dataframe against the submission csv file generated from the kaggle python script.</h3>
<pre class="r"><code>compare &lt;- data.frame(1:418)
compare &lt;- ifelse(output$Survived == submission$Survived, 1, 0)
compare &lt;- as.numeric(compare)
table(compare)</code></pre>
<pre><code>## compare
##   0   1 
##   9 409</code></pre>
</div>
<div id="we-see-that-409-of-the-passangers-match-between-the-kaggle-and-the-model-i-have-developed-which-suggests-that-my-solution-is-fairly-accurate.-furthermore-the-kaggle-model-uses-the-parch-variable-which-i-have-excluded-only-resulting-in-9-differnces-suggesting-that-the-parch-variable-is-not-a-very-high-yield-predictor." class="section level3">
<h3>We see that 409 of the passangers match between the Kaggle and the model I have developed which suggests that my solution is fairly accurate. Furthermore, the Kaggle model uses the Parch variable which I have excluded only resulting in 9 differnces suggesting that the Parch variable is not a very high-yield predictor.</h3>
</div>
</div>
